/*
 * Automatically generated by Magic.
 */
CREATE TABLE hyperlambda(
  hyperlambda_id integer not null primary key autoincrement,
  "code" text not null,
  "prompt" text,
  "validation" integer not null default 0
);

